spring:
#  jackson:
#    deserialization:
#        fail-on-unknown-properties: true

  datasource:
    username: sa
    password:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    hikari:
      jdbc-url: jdbc:h2:mem:testdb
#  datasource:
#    url: jdbc:mysql://localhost:3306/rest_api_exam?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
#    username: connectuser
#    password: connect123!@#
#    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        #          show_sql: true
#        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        dialect: org.hibernate.dialect.H2Dialect
        default_batch_fetch_size: 100

  devtools:
    livereload:
      enabled: true

  thymeleaf:
    cache: false
  session:
    store-type: jdbc

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

